### PR TITLE
Bump GitHub version to version 2.4.1

### PR DESCRIPTION
**Pull request by noloader**
Bump GitHub version to version 2.4.1

### CODE REVIEW

**Comment by mtesauro** [comment]
Thanks for this - I keep forgetting to rev the example :+1:

**Comment by noloader** [comment]
@mtesauro,

No problems. While I've got your ear, two questions...

1. Where is the mailing list or discussion board?
2. Do you want a PR for `README-PostgreSQL.md`?

I needed to create a HowTo for our internal team. The HowTo will be the basis of `README-PostgreSQL.md`. It will be released under the same license DefectDojo uses.

**Comment by mtesauro** [comment]
(1) Most discussion happens on #defectdojo on the OWASP Slack instance.  You can @ me there on Godojo questions.

(2) I assume README-PostgreSQL.md would be instructions for using Godojo with PostgreSQL, especially when it already exists and/or is separate from the Godojo installation.  On my TODO for this week is to rename the ./scripts directory to ./docs-and-scripts and start putting documentation there so it's in the repo.  I was also debating dropping things in GH wiki but I kinda prefer getting everything I need when I do a git clone rather then having to look at docs somewhere else.  SO, if you want, drop it in ./scripts or ./docs-and-scripts if I beat you to your PR.  I think that's a good place to gather related docs on using Godojo for now.

Cheers!

**Comment by noloader** [comment]
Thanks @mtesauro,

I started on a PR for Fedora support. It was intended to get beyond the *"Unsupported OS to bootstrap, quitting"* message. It is available at https://github.com/noloader/godojo/tree/fedora. Unfortunately, it is untested because I cannot get the installer to build on Fedora 35 or Ubuntu 20.04. I don't know the Go language so working though the problems is a bit much for me.

Would you like it as a PR?

**Comment by mtesauro** [comment]
Don't know how I missed this update but, sure a PR is fine.  If you do a PR, please do it against the dev branch. You can also just list out the OS commands that are needed to run on Fedora 35 and I can add those into godojo as well.

I'm currently working on extracting out to a separate package the addCmd, tryCmds, etc that I'm using to run OS commands so the code is less cluttered/cleaner so even just a list of Fedora commands is a great contribution.

I will also look at your fork to see if I can just pull out the Fedora specific stuff if a PR is hard to test on Fedora.  Based on the issue you added, I'm guessing Fedora has an older version of Go that 1.16.

**Pull request merged**
